name: Daily Pharmacy Update

on:
  schedule:
    - cron: '10 8 * * *'
      timezone: "Europe/Istanbul"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Скачиваем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # ИЗМЕНИЛИ С 18 НА 20!

      - name: Устанавливаем зависимости (cheerio)
        run: npm install cheerio

      - name: Запускаем скрипт сбора данных
        run: node fetch_pharmacies.js

      - name: Публикуем результат в ветку gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
